#!/usr/bin/env python3
"""
Vulti CLI Launcher

This is a convenience wrapper to launch the Vulti CLI.
Usage: ./vulti [options]
"""

if __name__ == "__main__":
    from cli import main
    import fire
    fire.Fire(main)
